#设置端口号
server:
  port: 9099
spring:
  #返回页面、数据中文乱码问题
  http:
      encoding:
        force: true
        charset: utf-8
        enabled: true
  tomcat:
      uri-encoding: UTF-8

  #解决程序读配置文件乱码问题
  messages:
      encoding: UTF-8
###########################kafak配置开始#############
#============== kafka ===================
  kafka:
  # 指定kafka 代理地址，可以多个
      bootstrap-servers: 127.0.0.1:9092

  #=============== producer  =======================
      producer:
          ## 重试次数
          retries: 3
          # 批量发送的消息数量
          batch-size: 16384
          # 32MB的批处理缓冲区
          buffer-memory: 33554432
          # 指定消息key和消息体的编解码方式
          key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
          value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
  #=============== consumer  =======================
      consumer:
          #  默认消费者组
          group-id: etl
          # 最早未被消费的offset
          auto-offset-reset: earliest
          # 批量一次最大拉取数据量
          max-poll-records: 1000
          #如果自动提交为true，则消费者偏移自动提交给Kafka的频率（以毫秒为单位），默认值为5000。
          auto-commit-interval: 1000
          enable-auto-commit: true
          # 指定消息key和消息体的编解码方式
          key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
          value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
###########################kafak配置结束#############

############数据库的配置文件#################
  datasource:
    url: jdbc:mysql://localhost:3306/bpos?serverTimezone=GMT%2B8
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

# Mybatis
mybatis:
  #实体类所做包
  type-aliases-package: com.xn.demo.domain
  #mapper.xml所在位置
  mapperLocations: classpath:mapper/*.xml

#配置动态topic
topicName:
    topic1: bt,lt
#配置消费者组
group-ids:
    name: xiaofei1
    name2: xiaofei2





